### ISSUE TITLE
Wie tar file erzeugen für OTA Update?

### ISSUE THREAD

**Issue by caco3** [Pfannex/OmniESP#18]
Für ein OTA Update erwartet OmniESP offenbar eine tar-Datei. Eine solche liegt ja dem `simpleSwitch` bei. Jedoch wird nirgends dokumentiert, wie dieses gebaut werden kann!
Der Upload direkt mit dem `firmware.bin` funktioniert leider nicht.

**Comment by caco3** [comment]
Ok, I found it:

There is a script `./tools/make-tarball.sh` which will create the tar file.

How ever it seems to rely on a git tag. You are not able to build it with uncommited data. And even if you commit it, you also have to tag it!

**Comment by caco3** [comment]
Ich hätte gerne eine Wiki-Seite beigesteuert, welche erläutert, wie man das tar-file erzeugt. Zudem fand ich diverse Typos und Unklarheiten in der Doku.

Leider ist es jedoch nicht möglich, das Wiki zu Forken und einen Pull-Request zu erzeugen! Siehe https://github.com/isaacs/github/issues/846 :(
Die darin vorgeschlagenen Lösungsansätze sind nicht sehr praktikabel...

**Comment by borisneubert** [comment]
Hallo,

im Wiki steht das hier:

`https://github.com/Pfannex/OmniESP/wiki/devicedevelopment`

Wohl nicht die Stelle, wo man das suchen würde :-(

Viele Grüße
Boris
